// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orzygtntiqzgpvczcgho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yenlndG50aXF6Z3B2Y3pjZ2hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MzQ2MDYsImV4cCI6MjA2NzMxMDYwNn0.FTOiAiLmZeVf-e-W7AJ6UHy7iVeWtjfLrrHuU-9G0vY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});